version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - rabbitmq_log:/var/log/rabbitmq
    networks:
      - rabbitmq_network
  front:
    image: nginx:1-alpine
    container_name: "nginx"
    ports:
      - "8085:80"
    volumes:
      - './Front/:/var/www/html'
      - './Front/Config/default.conf/:/etc/nginx/conf.d/default.conf'
volumes:
  rabbitmq_data:
  rabbitmq_log:

networks:
  rabbitmq_network:
    driver: bridge
